apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: playeconomy-host
spec:
  hostname: wa-playeconomy.eastus.cloudapp.azure.com
  acmeProvider:
    email: wallacewast@gmail.com
  tlsSecret:
    name: playeconomy-tls
